CREATE TABLE IF NOT EXISTS encuestas(
    nro_encuesta INT NOT NULL AUTO_INCREMENT,
    cantidad_empresas ENUM('1','+1') NOT NULL,
    cantidad_ingresada_empresas INT,
    cantidad_empleados_dedicados ENUM('parcial','fulltime','+1') NOT NULL,
    horas_mensuales INT,
    cantidad_empleados_fulltime INT,
    cantidad_veces_viaja ENUM('2','3','+3') NOT NULL,
    cantidad_ingresada_veces_viaja INT,
    gasto_viaticos DECIMAL(4,2) NOT NULL,
    horas_insumidas INT NOT NULL,
    tiempo_incluido_en_horas_mensuales BOOLEAN,
    tipo_tmpresora ENUM('chorro','laser') NOT NULL,
    frecuancia_cambio_cartuchos INT,
    frecuancia_cambio_toner INT,
    uso_impresor BOOLEAN NOT NULL,
    procentaje_uso_impresora DECIMAL(4,2),
    opcion_cantidad_resmas ENUM('-1','1','+1') NOT NULL,
    cantidad_hojas INT,
    cantidad_resmas INT,
    usa_fotocopias BOOLEAN NOT NULL,
    cantidad_fotocopias INT,
    cantidad_carpetas ENUM('0','1','+1') NOT NULL,
    cantidad_ingresada_carpetas INT,
    cantidad_nepacos ENUM('0','1','+1') NOT NULL,
    cantidad_ingresada_nepacos INT,
    cantidad_caratulas ENUM('0','4','+4') NOT NULL,
    cantidad_ingresada_caratulas INT,
    cantidad_reimpresion INT NOT NULL,
    costo_archivado DECIMAL(7,2) NOT NULL,
    costo_riesgos_laborales DECIMAL(7,2) NOT NULL,
    tiempo_promedio_revision DECIMAL(4,2) NOT NULL,
    costo_estimado_riesgos DECIMAL(7,2) NOT NULL,
    inconvenientes TEXT,
    tiene_conexion_internet BOOLEAN NOT NULL,
    costo_conexion_internet DECIAML(7,2),
    PRIMARY KEY (nro_encuesta)
)ENGINE MyISAM DEFAULT CHARACTER SET=utf8;

CREATE TABLE IF NOT EXISTS empleados_x_empresa(
    nro_encuesta INT NOT NULL,
    cantidad_empleados INT NOT NULL,
    cantidad_empresas INT,
    PRIMARY KEY (nro_encuesta, cantidad_empleados),
    FOREIGN KEY (nro_encuesta) REFERENCES encuestas (nro_encuesta)
)ENGINE MyISAM DEFAULT CHARACTER SET=utf8;